import shutil
from os.path import join

Import("env")

# Path of the .hex file generated by PlatformIO
hex_path = join(env.subst("$BUILD_DIR"), "firmware.hex")

# Copy it to your project folder after build
def copy_hex(source, target, env):
    shutil.copy(hex_path, join(env.subst("$PROJECT_DIR"), "firmware.hex"))
    print("✅ firmware.hex copied to project root")

env.AddPostAction("$BUILD_DIR/${PROGNAME}.hex", copy_hex)
